name = "finance-tracker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages / Workers will pick up these bindings automatically
[[d1_databases]]
binding = "DB"
database_name = "finance-tracker-db"
database_id = "2036d06c-c897-4d1d-9422-6e898854d700"
